### ISSUE TITLE
possible to change todo state in sidebar?

### ISSUE THREAD

**Issue by titaniumbones** [alphapapa/org-sidebar#10]
if it were possible to change the todo state of an item in the sidebar, that would really increase the value for me! But it doesn't seem like that is easily available give nthe construction of htose buffers (from what I can tell).

**Comment by alphapapa** [comment]
That would be very useful, yes.  The current implementation renders items using a function in `org-sidebar`, which doesn't work with `org-agenda` commands.  I will probably rewrite that code to basically wrap `org-ql-search`, which would make the item sidebar buffers into `org-ql-view` buffers, which would allow you to use `org-agenda` commands that work in `org-ql-view` buffers, such as scheduling, todo, etc.

**Comment by alphapapa** [comment]
FYI, this change has been made.  Feel free to try it and let me know how it works for you.  Thanks.
