### ISSUE TITLE
apply: Cannot open load file: No such file or directory, org-ql-agenda

### ISSUE THREAD

**Issue by avkoval** [alphapapa/org-sidebar#13]
When package is installed fresh, it works
But after

1. Quit emacs
2. Run it again

M-x org-sidebar-tree

> apply: Cannot open load file: No such file or directory, org-ql-agenda

**Comment by avkoval** [comment]
```
  drwxr-xr-x   2 avkoval avkoval  4096 Oct  9 11:35 org-sidebar-20191004.1824
  drwxr-xr-x   2 avkoval avkoval  4096 Oct  9 11:35 org-ql-20191009.202
```

**Comment by avkoval** [comment]
I see that in org-ql.info:

```
   *Removed*
   • Macro org-ql-agenda.  Instead, use function org-ql-search.  See
     also command org-ql-view, etc.
```
But its still being referenced from org-sidebar:

```
lisp/org-sidebar.el
6    ;; Package-Requires: ((emacs "25.1") (s "1.10.0") (dash "2.13") (org "9.0") (org-ql) (org-ql-agenda) (org-super-agenda "1.0"))
23   ;; org-ql and org-ql-agenda may be found at <http://github.com/alphapapa/org-ql>.  Then put
60   (require 'org-ql-agenda)
111  (defcustom org-sidebar-format-fn #'org-ql-agenda--format-element
114  Generally, `org-ql-agenda--format-element' should be used; if
202  items are formatted by `org-ql-agenda--format-element', it might
```

**Comment by alphapapa** [comment]
`org-ql-agenda` is not referenced in `master`.  You need to upgrade the package and delete old versions of it.

**Comment by avkoval** [comment]
Uh-oh, I've deleted it several times, including an attempt to remove whole 'elpa' directory and starting over until I've realized that as early adopter I've got org-sidebar placed into custom 'lisp' directory since February. Sorry for noice, now all is well! :-) And given this chance, would like to thank you for the useful package!

**Comment by alphapapa** [comment]
> Uh-oh, I've deleted it several times, including an attempt to remove whole 'elpa' directory and starting over until I've realized that as early adopter I've got org-sidebar placed into custom 'lisp' directory since February

That happened to me a few days ago with one of my own packages as well.  :)

> And given this chance, would like to thank you for the useful package!

Thanks for the kind words.  Please let me know if you have any feedback.
