### ISSUE TITLE
How to use with outshine?

### ISSUE THREAD

**Issue by obar** [alphapapa/org-sidebar#16]
Is it possible to (without great code surgery) use this with [outshine-mode](https://github.com/alphapapa/outshine), or is it too different from an org file?

**Comment by alphapapa** [comment]
It's not possible, because it's not an Org buffer, nor is it an outline buffer.  What are you wanting to accomplish with it?

**Comment by obar** [comment]
I was wondering if something like the tree view navigation (and rearranging) would be possible with a large emacs config. Not a burning need by any measure, just had been curious about it. Thanks!

**Comment by alphapapa** [comment]
I plan for `org-ql` to have a tree-based grouping view (e.g. like https://github.com/alphapapa/sbuffer.el; also see the branch on `org-ql`'s repo).  Then `org-sidebar` will probably use that and gain something like this.
