### ISSUE TITLE
Error with backlinks when org-agenda-files is a file containing the agenda files list

### ISSUE THREAD

**Issue by gdindi** [alphapapa/org-sidebar#17]
Hi,
First of all, thanks for this very useful package. I am very interested by the recent addition of org-sidebar-backlinks for my Zettelkasten implementation. I am experiencing an issue. If I use

`(setq org-agenda-files (quote ("~/org/admin.org" ~/org/zettels.org")))`

the `org-sidebar-backlinks` works fine. However, if I do:
`(setq org-agenda-files "~/org/agenda-files.org")`

where "~/org/agenda-files.org" is a file containing the list of my agenda files, I get an error like this:

`mapcar: Wrong type argument: stringp, 47`

In order to check that there is no problem with other things in my config, I have run this with

emacs -Q -l test-init.el

where test-init.el is

```
(setq package-enable-at-startup nil)
(package-initialize)
(require 'org)
(require 'ob-tangle)

(require 'org-ql)
(require 'org-sidebar)
(require 'org-ql-view)
(require 'org-ql-search)
(require 'org-super-agenda)
(setq org-agenda-files "~/org/agenda-files.org")

```

Any help would be appreciated.

Thanks.

**Comment by alphapapa** [comment]
Hi,

Please call the `org-agenda-files` function rather than using the variable's value directly.

Note also that the underlying functionality for this command is provided by `org-ql`, not directly by `org-sidebar`.

Thanks.

**Comment by gdindi** [comment]
Hi,
I don't understand your suggestion. Where do I need to call the org-agenda-files function?
Thanks again.

**Comment by gdindi** [comment]
I have moved my question to https://github.com/alphapapa/org-ql/issues/104
