### ISSUE TITLE
Posibility to exclude some headlines by tags

### ISSUE THREAD

**Issue by llcc** [alphapapa/org-sidebar#19]
Thanks for this impressive package. I use it a lot in my daily life.

I use org-drill a lot, so my org file is full of drill headlines, of course with its according deadline keyword. When I call `org-sidebar-toggle`, those headlines all go to the up-coming buffer, which should not be included basically, since they are not always related to any todo works.

So I would like to request a new feature to support any exclusion of specific headlines, like using org-tags?

Thanks if you can offer some ideas.

**Comment by alphapapa** [comment]
Thanks for the kind words.

If you narrow the Org buffer before calling `org-sidebar`, it will only show headings from the narrowed subtree.  You could use, e.g. `org-tree-to-indirect-buffer`.

> So I would like to request a new feature to support any exclusion of specific headlines, like using org-tags?

You can use `org-sidebar-ql` with any query you like.

**Comment by llcc** [comment]
Hi @alphapapa 

Sorry to reply late. Thanks for your answer, I will check the codes to find if a possible solution exists.
