### ISSUE TITLE
Display tree structure only, hide note text at the beginning

### ISSUE THREAD

**Issue by yuchen-lea** [alphapapa/org-sidebar#23]
Thanks for this wonderful work. It helps me a lot.

I expect this only display tree structure of headlines. It works great when I narrow buffer to some headings. For example:

> \* head 1
> text 1
> ** head 1.1
> text 1.1
> ** head 1.2
> text 1.2

Sidebar:

> \* head 1
> ** head 1.1
> ** head 1.2

However, the sidebar for file buffer shows the note at top. For example:

> #+Title: Emacs
> file text
> \* head 1
> text 1
> ** head 1.1
> text 1.1
> ** head 1.2
> text 1.2
> \* head 2
> text 2

Sidebar:

> #+Title: Emacs
> file text
> \* head 1
> ** head 1.1
> ** head 1.2
> \* head 2

As for me, and maybe for most people, the expected sidebar tree is:

> \* head 1
> ** head 1.1
> ** head 1.2
> \* head 2

It would be great if you can offer some ideas.

Environments:  
GNU Emacs 26.3 (build 1, x86_64-apple-darwin19.3.0, Carbon Version 162 AppKit 1894.3) of 2020-03-07
Org mode version 9.1.2
org-sidebar 0.3

**Comment by alphapapa** [comment]
Thanks, that should fix it.  Please let me know how it works for you.

**Comment by yuchen-lea** [comment]
Yeah, already fixed! Many thanks for your effort!
