### ISSUE TITLE
Error launching org-sidebar-backlinks?

### ISSUE THREAD

**Issue by Ypot** [alphapapa/org-sidebar#24]
Very attractive feature, but which never worked for me. This is the message I get when M-x org-sidebar-backlinks:
`helm-M-x: Wrong type argument: sequencep, :title`

And a new buffer called org-ql-sidebar is created in the background with the backlinks. Not sure if this is the expected behavior.

**Comment by alphapapa** [comment]
You need to upgrade the Emacs packages you have installed.
