### ISSUE TITLE
org-sidebar-refresh doesn't work

### ISSUE THREAD

**Issue by darioceccoli** [alphapapa/org-sidebar#26]
`org-sidebar-refresh` at the moment doesn't work on the `master` branch because it refers to `org-sidebar-display-buffers` which doesn't exists.

I think the right variable there is `org-sidebar-sidebar-buffers` and I guess the original intention was to refactor `org-sidebar-sidebar-buffers` into `org-sidebar-display-buffers`.

**Comment by alphapapa** [comment]
Thanks.  I thought I tested that when I refactored, but I must have done something wrong.

**Comment by alphapapa** [comment]
Thanks for your patience!
