### ISSUE TITLE
Add a variable to customise which sorts of links get searched for with `org-sidebar-backlinks`

### ISSUE THREAD

**Issue by spacekitteh** [alphapapa/org-sidebar#27]
As an avid user of `org-brain`, I'd very much like the ability for `org-sidebar-backlinks` to display various link types in addition to just `id:`.

**Comment by alphapapa** [comment]
Implementing that functionality would require much more than a variable.  It would require implementing what `org-brain` implements, i.e. maintaining a database of links between entries and a way to query it.

Since `org-brain` provides that functionality, why are you seeking it here?
