### ISSUE TITLE
How to have sidebar tree be read-only by default?

### ISSUE THREAD

**Issue by coffeepenbit** [alphapapa/org-sidebar#29]
Thanks for this great package! It helps me a lot.

Unfortunately, I keep accidentally typing in the indirect sidebar tree buffer and making unintended changes.

Is there a way I can make the sidebar tree be `read-only-mode` by default? I'm not sure how I would go about doing this.

**Comment by alphapapa** [comment]
That functionality is not built-in.  You would need to write a little Elisp code.  It would be a good opportunity to learn how to make some simple customizations like this.  Please consider asking this question somewhere like old.reddit.com/r/emacs where other people can also offer answers and benefit from reading them.

**Comment by coffeepenbit** [comment]
Thanks, I'll do that!
