### ISSUE TITLE
Warning: Unused lexical variable ‘group’

### ISSUE THREAD

**Issue by vikasrawal** [alphapapa/org-sidebar#3]
I just get this when I call org-sidebar  (M-x org-sidebar):

Warning: Unused lexical variable ‘group’

Do I need some customization before I use it?

**Comment by alphapapa** [comment]
No, you can ignore that warning.

**Comment by alphapapa** [comment]
Please see the commit I just pushed, which should solve that warning.  Thanks.

**Comment by vikasrawal** [comment]
Now I get all these:
Warning: Unused lexical variable ‘buffer-or-path’
Warning: Unused lexical variable ‘group’
Warning: Unused lexical variable ‘super-groups’
Warning: Unused lexical variable ‘source-buffer’

And I do not get any sidebar.

**Comment by alphapapa** [comment]
I get no warnings and it works for me.  Try reinstalling the package.  I recommend using Quelpa, like this:

```el
(use-package org-sidebar
  :quelpa (org-sidebar :fetcher github :repo "alphapapa/org-sidebar"))
```

I use this to make it easy: https://github.com/alphapapa/unpackaged.el#upgrade-a-quelpa-use-package-forms-package

**Comment by vikasrawal** [comment]
Now, after I start emacs, open an org buffer, and do M-x org-sidebar:

I get the message: Function provided is already compiled [2 times]

No sidebar still.

Is there something else I need to install?

**Comment by alphapapa** [comment]
Thanks for reporting these problems.  I just pushed some fixes and tested in a clean Emacs, and it works now.  Please install/update the package again and let me know if it works for you.

**Comment by vikasrawal** [comment]
I realise the message "Function provided is already compiled" comes from a file that does not have any TODO items but has some scheduled items that do not have a TODO state. Ideally, such items should show in the agenda. Once I put a TODO state for at least one item in the file, everything works.

**Comment by alphapapa** [comment]
> I realise the message "Function provided is already compiled"

Please ignore that message, it's not relevant to the problem you seem to be having.

> a file that does not have any TODO items but has some scheduled items that do not have a TODO state. Ideally, such items should show in the agenda

You'll have to be more specific.

Also, we need to use more specific terms.  The Org Agenda is a specific tool built-in to Org mode.  `org-sidebar` does not provide an Org Agenda view.  Some of its functionality is similar, but it is not the same tool.  So there is no "agenda" in `org-sidebar`.

**Comment by vikasrawal** [comment]
Org-sidebar uses the term "Agenda items". Hence the confusion. All I was saying is that, if my file has scheduled items but no todo item, the sidebar is not shown. It just gives the message: "Function provided is already compiled", and nothing happens. A better behaviour would be to show the top section of the sidebar with Scheduled items.

**Comment by alphapapa** [comment]
> I got confused because org-sidebar uses the term "Agenda items" and since I was originally looking for a solution to show my agenda in the sidebar.

Yes, the terms are a bit confusing, sorry about that.  It's hard to find a way to say, "This is sort of like the Org Agenda, but not exactly."  Please let me know if you have any suggestions for this.

> All I was saying is that, if my file has scheduled items but no todo item, the sidebar is not shown. It just gives the message: "Function provided is already compiled", and nothing happens. A better behaviour would be to show the top section of the sidebar with Scheduled items.

This isn't the case for me.  For example, with this test file:
```org
blahblah

* A
SCHEDULED: <2019-07-19 Fri>

blah
```
When I run `org-sidebar`, I get one sidebar window that says, `org-sidebar: agenda items in file.org`, and it displays:
```
    A  today
```
If it's not working for you, be sure that all of the related packages are up-to-date.

**Comment by alphapapa** [comment]
Please let me know if you need more help.
