### ISSUE TITLE
Backlinks not working

### ISSUE THREAD

**Issue by konstruktiv** [alphapapa/org-sidebar#31]
`org-sidebar-backlinks` is not working as expected. Instead of showing Entry 2 as a backlink for Entry 1, the list of backlinks is empty for the following example:

```
* Entry 1
:PROPERTIES:
:CUSTOM_ID: entry1
:END:

* Entry 2
:PROPERTIES:
:CUSTOM_ID: entry2
:END:

[[#entry1]]
```

**Comment by egh** [comment]
`org-sidebar-backlinks` searches `org-directory` by default. Probably you need a slightly modified function.

**Comment by alphapapa** [comment]
@konstruktiv Sorry for overlooking this.  Erik is probably right, but you didn't give details about the file or buffer you're searching.

Anyway, this feature is somewhat primitive and inflexible as-written.  If you really need backlinks, a package like org-roam would probably work better for you.

@egh Thanks!

**Comment by konstruktiv** [comment]
@alphapapa Sorry I can't give more info as I moved to [org-super-links](https://github.com/toshism/org-super-links) which has working backlinks.

Anyway, thanks for org-sidebar. I hope I will have a chance to revisit the package some time.

**Comment by alphapapa** [comment]
Thanks.
