### ISSUE TITLE
org-sidebar must be called before org-sidebar-backlinks?

### ISSUE THREAD

**Issue by konstruktiv** [alphapapa/org-sidebar#32]
When I call `org-sidebar-backlinks` before calling `org-sidebar`, I get the error message `org-sidebar-backlinks: Symbol’s function definition is void: org-ql-search-directories-files`.

Is this expected behavior? It doesn't seem to be documented and can be confusing.

**Comment by alphapapa** [comment]
Thanks, that's the result of a simple oversight: `(require 'org-ql-search)` should be present in `org-sidebar.el`.
