### ISSUE TITLE
Symbol’s value as variable is void: accessor-init

### ISSUE THREAD

**Issue by basaran** [alphapapa/org-sidebar#33]
Hello,

All org-sidebar commands, are returning these errors at the messages buffer:

```
Eager macro-expansion failure: (void-variable accessor-init) [2 times]
condition-case: Symbol’s value as variable is void: accessor-init
```

I'm using spacemacs latest on Windows 10:

GNU Emacs 26.1 (build 1, x86_64-w64-mingw32)

**Comment by alphapapa** [comment]
You have a package installation problem.  As well, your version of Emacs is quite outdated, which may be part of the problem.  I would recommend upgrading Emacs and reinstalling the relevant packages from scratch.
