### ISSUE TITLE
sidebar doesn't toggle on emacs 28/tab bar mode?

### ISSUE THREAD

**Issue by titaniumbones** [alphapapa/org-sidebar#34]
Haven't been able to run systematic tests yet but the sidebar tree does not seem to toggle *off* after being activated in Emacs 28 with tab-bar-mode switched on.  the regular sidebar will still toggle off as expected.  Somewhat hectic time here but will try to poke around and investigate.

**Comment by alphapapa** [comment]
I don't know how `tab-bar-mode` could affect the toggling behavior.  Let me know.

**Comment by mkb6** [comment]
I have the same problem with emacs 26.3 (Ubuntu 20.04) with the sidebar-**tree**-toggle. It toggles on, but not off. The "normal" sidebar-toggle works.

I'm not sure how I can give helpful information, I started using emacs only two weeks ago. Anyway, thanks for this package and also for super-agenda!

**Comment by alphapapa** [comment]
@mkb6 Thanks, I think I found the problem.  Please upgrade the package and let me know how it works for you.  (If you installed from MELPA, you'll have to wait until the new version is packaged a few hours from now.)

@titaniumbones I think the problem was unrelated to the tab-bar.  Please let me know how this works for you.  If the tab-bar is still causing a problem, let me know and I'll reopen this.  Thanks.

**Comment by mkb6** [comment]
yess it works for me now :)

This is a really cool package - I started with a single org-file two weeks ago, but at some point it grew too big for me to keep a good overview so I started to split everything in several files... but then I got lost in switching buffers and refiling so it didn't really solved the problem, but the sidebar-tree does.

Thanks for your work!

**Comment by alphapapa** [comment]
@mkb6 Thanks, I'm glad to hear it.

I can also recommend installing the package `helm-org`, as its commands like `helm-org-in-buffer-headings` make it very quick and easy to jump around in an Org file.  It's indispensable to me.

And, of course, see some of my other Org packages, like `org-rifle` and `org-ql` (including `helm-org-ql`), which will also help you with searching.  :)  `org-recent-headings` and `org-bookmark-heading` will also help with referring back to certain headings you access frequently.

**Comment by mkb6** [comment]
Thanks a lot, I will definitely check them out :)
