### ISSUE TITLE
org-sidebar-tree "follow" behaviour only working with mouse

### ISSUE THREAD

**Issue by Gahamelas** [alphapapa/org-sidebar#39]
Hi!

Regarding `Org-sidebar-tree`, I notice that on my Emacs the keyboard movement through the tree headlines does not update the `org buffer`. Only when using the mouse cursor it does (when clicking, not when navigating with keyboard). Is this the expected behaviour?

**Comment by alphapapa** [comment]
Please see https://github.com/alphapapa/org-sidebar/blob/67fe1b5c6c879e14d34c34eec2190e9719046b6c/org-sidebar.el#L370

**Comment by Gahamelas** [comment]
I see now! Thanks. The problem is that when using ENTER, it jumps to the original entry. Is there a way to "follow" without jumping to the original entry?

**Comment by alphapapa** [comment]
I don't understand what you mean.  Please explain.

**Comment by Gahamelas** [comment]
When I am in the org-sidebar, I move up and down with the keyboard. When I want to update my org file on the right of the sidebar to point to where I am on the org-sidebar, I press ENTER. But then the cursor jumps to the org buffer on the right. Is it possible that I stay on the org-sidebar while having a peek at the contents on the org buffer on ther right? Hope I made myself understood. English is not my native language.

**Comment by alphapapa** [comment]
Such a command is not currently implemented.
