### ISSUE TITLE
How to get the agenda from all the agenda files?

### ISSUE THREAD

**Issue by vikasrawal** [alphapapa/org-sidebar#4]
Can I use this to see agenda from all my agenda files in the sidebar? Or does it only work with the current buffer?

**Comment by alphapapa** [comment]
The two built-in sidebars use the current buffer, but you can write a sidebar function to display whatever items you want.  The API for this is still awkward and I hope to improve it.  In the meantime, try this:
```el
(org-sidebar-def-item-buffer-fn all-agenda-files
  "all agenda-file items"
  (cl-flet ((date-header (item)
                         (propertize (org-timestamp-format (or (org-element-property :scheduled item)
                                                               (org-element-property :deadline item))
                                                           org-sidebar-date-format)
                                     'face '(:inherit variable-pitch :weight bold))))
    (let ((items (org-ql (org-agenda-files)
                   (and (not (done))
                        (or (todo "TODAY" "IMPORTANT")
                            (deadline <=)
                            (date = today)
                            (and (scheduled <=)
                                 (tags "personal"))
                            (and (todo)
                                 (tags "now"))))
                   :sort (date todo priority))))
      (if group
          (-group-by #'date-header items)
        items))))

(org-sidebar :buffer-fns '(org-sidebar--all-agenda-files-buffer)
             :super-groups t)
```

You can adjust the query in the `org-ql` block as desired.  That one is similar to a standard Org Agenda with some customizations.

**Comment by vikasrawal** [comment]
This does not seem to work. I turned out the debugger and it gave an error as follows:

Debugger entered--Lisp error: (error "Unknown date-element type: active-range")
  signal(error ("Unknown date-element type: active-range"))
  error("Unknown date-element type: %s" active-range)
  org-ql--date-type-p(:scheduled <= nil)
  scheduled(<=)
  #f(compiled-function () #<bytecode 0x1c2e87d>)()
....
.....

**Comment by alphapapa** [comment]
What version of Emacs and Org are you using?

**Comment by vikasrawal** [comment]
GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of
2019-04-12
Org mode version 9.2.4 (9.2.4-10-g3b006f-elpaplus @
/home/vikas/.emacs.d/elpa/org-plus-contrib-20190715/)

**Comment by alphapapa** [comment]
That would seem to indicate that you have an entry in that Org file with a `SCHEDULED:` planning line that has a timestamp range rather than a single timestamp, e.g.:

```org
* Heading
SCHEDULED: <2019-07-17 Thu 12:00>--<2019-07-18 Fri 12:00>
```
Can you confirm that?

If so, I don't think that is valid in Org.  According to the Org manual, `SCHEDULED` is supposed to be used for a date on which you plan to start working on an entry.

**Comment by alphapapa** [comment]
If it helps, I just pushed a new commit to `org-ql` that gives a more detailed error message.  You could upgrade `org-ql` and perform the same action and it will show you where the bad date range is.

**Comment by vikasrawal** [comment]
That would seem to indicate that you have an entry in that Org file with a
> SCHEDULED: planning line that has a timestamp range rather than a single
> timestamp, e.g.:
>
> * Heading
> SCHEDULED: <2019-07-17 Thu 12:00>--<2019-07-18 Fri 12:00>
>
> Can you confirm that?
>

Oh, yes. I am guilty of shaving made that mistake. Just check es the
documentation and it is indeed as you say.

**Comment by alphapapa** [comment]
Okay, well, I'm not sure if that's actually a mistake.  It doesn't seem to fit with what the manual says the intended use of the `SCHEDULED` line is, but many, many Org users don't know about that and don't use it that way.  So we probably need to handle ranges there anyway.

And, in fact, `org-ql` was [supposed](https://github.com/alphapapa/org-ql/commit/c5599a6030eb6f0b8e7a181cbbeb7c323a037d63) to handle that, but I made a mistake and didn't implement it properly.  So I'll fix that now, in `org-ql`, and you shouldn't have that problem anymore.

Thanks for reporting these issues.  As you can tell, org-sidebar is still somewhat experimental and needs a lot of polishing.  After org-ql gets published on MELPA, I'll work on that and hope to publish org-sidebar on MELPA too.

**Comment by alphapapa** [comment]
The fix is pushed to org-ql now.  Thanks.
