### ISSUE TITLE
org-sidebar: Symbol’s function definition is void: make-org-sidebar 

### ISSUE THREAD

**Issue by elge70** [alphapapa/org-sidebar#41]
In the examples given in https://github.com/alphapapa/org-sidebar/blob/master/examples.org , make-org-sidebar function is used to create a sidebar. I am getting error while using the function. Could you please update the example.org file with updates

Error is 

org-sidebar: Symbol’s function definition is void: make-org-sidebar 

If I use the example 

(defun my/org-sidebar ()
  "Display my Org Sidebar."
  (interactive)
  (org-sidebar
   :sidebars (make-org-sidebar
              :name "My Sidebar"
              :description "My sidebar items"
              :items (org-ql (org-agenda-files)
                       (and (not (done))
                            (or (deadline auto)
                                (scheduled :on today)))
                       :action element-with-markers))))

= George

**Comment by alphapapa** [comment]
https://github.com/alphapapa/org-sidebar/issues/28
