### ISSUE TITLE
Inconsistency of todo keyword faces when faces defined as local variables 

### ISSUE THREAD

**Issue by llcc** [alphapapa/org-sidebar#42]
org-sidebar uses the global todo keyword faces. Faces defined in file seems not used rightly in org-sidebar.
You can reproduce the problem by using the following example. Thanks.

```org
#+TITLE:TODO keyword face problems

* TODO task 1

** TODO a child task
SCHEDULED: <2020-12-27 Sun>

** TODO another child task
SCHEDULED: <2020-12-28 Mon>

* NEXT Task 2
SCHEDULED: <2020-12-29 Tue>

* DONE Task 3
DEADLINE: <2020-12-30 Wed>


#+TODO: TODO(t) NEXT(n) | DONE(d)
# Local Variables:
# org-todo-keyword-faces: (("todo" . "red") ("NEXT" . "pink") ("DONE" . "green"))
# End:

```
![image](https://user-images.githubusercontent.com/3996879/103162924-5669a800-483a-11eb-94cf-f274ecd52a31.png)

**Comment by alphapapa** [comment]
Thanks for the thorough report.  However, please note that those sidebar views are provided by `org-ql`, not by code in this package, so this issue should be reported against `org-ql`.

If you'd like to file it there, I'm willing to consider it, however I would consider this to be an edge case that I'm not sure it would be worth supporting, so I won't promise to implement it.

**Comment by llcc** [comment]
refer to https://github.com/alphapapa/org-ql/issues/174#issue-775830436
