### ISSUE TITLE
Ability of zooming in/out into the sidebar independently of the main window.

### ISSUE THREAD

**Issue by iburunat** [alphapapa/org-sidebar#44]
Wonderful package, exactly what I was looking for.
An idea (if not implemented yet—I couldn't find it) would be for the sidebar window to be zoomable (out) without affecting the main window. This is useful in the case of a long list of headings that one wants to see at once.

**Comment by alphapapa** [comment]
I don't understand what you mean. Would you give an example please?

**Comment by iburunat** [comment]
It seems I don't have this problem anymore. Before, whenever I did `C-+` (`text-scale-increase`), both sidebar and main window would increase simultaneously, rather than independently. I will close this issue. Apologies!
