### ISSUE TITLE
*Compile-Log* warning on on 28.0.50 nativecomp

### ISSUE THREAD

**Issue by arozbiz** [alphapapa/org-sidebar#48]
I'm running 28.0.50 with nativecomp () and have org-sidebar installed with `(use-package org-sidebar)`. On startup I get the following `*Compile-Log*`  warning:
```Warning (bytecomp): pcase pattern `(,(or 'tags-inherited 'inherited-tags 'tags-i 'itags)) shadowed by previous pcase pattern```

Running M-x version gives me the following: `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2021-04-09`

**Comment by alphapapa** [comment]
That's a bytecomp warning, not a native-comp warning, and it refers to code in org-ql rather than in org-sidebar.  As well, Emacs 28 is not yet released, so feel free to report this if it happens after Emacs 28 is released.  Thanks.
