### ISSUE TITLE
are examples in `examples.org` still correct?

### ISSUE THREAD

**Issue by titaniumbones** [alphapapa/org-sidebar#50]
examples in `examples.org` do not work for me out of the box, and it also seems that they refer to a non-existent `make-org-sidebar` function while also giving a named `:sidebars` argument to `org-sidebar`, which does not seem to want such an argument. 

Looking back in git history, it sort of seems that this was how org-sidebar used to work, but that it's changed a lot since then.  

Wouldl ove some up to date versions ofhtese ommands if you have them lying around!

Thanks,

matt

**Comment by alphapapa** [comment]
Sorry, the examples do need to be updated.  Please see #28.  However, the code in org-sidebar is pretty simple; see these two default functions for models: https://github.com/alphapapa/org-sidebar/blob/67fe1b5c6c879e14d34c34eec2190e9719046b6c/org-sidebar.el#L323
