### ISSUE TITLE
Prevent emacs from keeping all buffers open

### ISSUE THREAD

**Issue by student-sx** [alphapapa/org-sidebar#58]
If I start `org-sidebar-tree` and use it to navigate to various sections of my org-file, it opens each time a new buffer containing the selected section. 

However the previously seen sections remain open as buffers in the background. 

Is there a good reason for this behavior? How can I turn it off (i.e. only the buffer displaying the last selected section says open)?

**Comment by alphapapa** [comment]
Please see option `org-sidebar-jump-indirect`.

**Comment by student-sx** [comment]
Thanks, however I didn't find out of how to make it work. First I looked for a documentation of this variable, but didn't find any. In the source code of `org-sidebar.el` it appears to be set to be true by default (but the variable doesn't seem to be used in the rest of the source code). Setting `(setq org-sidebar-jump-indirect nil)` didn't have any effect. So it would be great, if you could add some more details.

**Comment by alphapapa** [comment]
Oops, I meant this: https://github.com/alphapapa/org-sidebar/blob/288703b897449f5110c9c76e78eb9a928ffc0dcd/org-sidebar.el#L390

Please see `M-x customize-group RET org-sidebar RET` for more options.
