### ISSUE TITLE
Don't just show current buffer's org?

### ISSUE THREAD

**Issue by theesfeld** [alphapapa/org-sidebar#62]
I would like to figure out how to have org-sidebar show ALL of my todo items, not just the current buffer. How can I do this? I am using doom emacs

**Comment by alphapapa** [comment]
You'll need to define a function like this one: https://github.com/alphapapa/org-sidebar/blob/288703b897449f5110c9c76e78eb9a928ffc0dcd/org-sidebar.el#L343
