### ISSUE TITLE
Can't use tab complete in helm find files when org-sidebar is active

### ISSUE THREAD

**Issue by tsdye** [alphapapa/org-sidebar#8]
When org-sidebar is active, tab completion in helm find files returns this error message:

split-window: Cannot split side window or parent of side window

This happens even if point is not in the sidebar.

Closing the sidebar restores the expected tab completion behavior.

Let me know if you have questions.

**Comment by alphapapa** [comment]
That would indicate a bug in Helm, but I'd be surprised if it's not fixed already, because it works for me.  Try upgrading Helm.

**Comment by tsdye** [comment]
Thanks.  It does appear to a Helm issue: https://github.com/emacs-helm/helm/pull/2200.
